version: '3.8'

services:
  pages-service:
    build: .
    container_name: pages-service-express
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - backboard-network

networks:
  backboard-network:
    external: true

